GeographicLib: GeographicLib::TransverseMercator Class Reference
GeographicLib::TransverseMercator Class Reference
Transverse Mercator projection.
#include <GeographicLib/TransverseMercator.hpp>
Public Member Functions
TransverseMercator (real a, real f, real k0)
void Forward (real lon0, real lat, real lon, real &x, real &y, real &gamma, real &k) const
void Reverse (real lon0, real x, real y, real &lat, real &lon, real &gamma, real &k) const
void Forward (real lon0, real lat, real lon, real &x, real &y) const
void Reverse (real lon0, real x, real y, real &lat, real &lon) const
Inspector functions
Math::real MajorRadius () const
Math::real Flattening () const
Math::real CentralScale () const
Static Public Member Functions
static const TransverseMercator & UTM ()
Friends
class Ellipsoid
Detailed Description
Transverse Mercator projection.
This uses Krüger's method which evaluates the projection and its inverse in terms of a series. See
L. Krüger, Konforme Abbildung des Erdellipsoids in der Ebene (Conformal mapping of the ellipsoidal earth to the plane), Royal Prussian Geodetic Institute, New Series 52, 172 pp. (1912).
C. F. F. Karney, Transverse Mercator with an accuracy of a few nanometers, J. Geodesy 85(8), 475–485 (Aug. 2011); preprint arXiv:1002.1417.
Krüger's method has been extended from 4th to 6th order. The maximum error is 5 nm (5 nanometers), ground distance, for all positions within 35 degrees of the central meridian. The error in the convergence is 2 × 10−15" and the relative error in the scale is 6 × 10−12%%. See Sec. 4 of arXiv:1002.1417 for details. The speed penalty in going to 6th order is only about 1%.
There's a singularity in the projection at φ = 0°, λ − λ0 = ±(1 − e)90° (≈ ±82.6° for the WGS84 ellipsoid), where e is the eccentricity. Beyond this point, the series ceases to converge and the results from this method will be garbage. To be on the safe side, don't use this method if the angular distance from the central meridian exceeds (1 − 2e)90° (≈ 75° for the WGS84 ellipsoid)
TransverseMercatorExact is an alternative implementation of the projection using exact formulas which yield accurate (to 8 nm) results over the entire ellipsoid.
The ellipsoid parameters and the central scale are set in the constructor. The central meridian (which is a trivial shift of the longitude) is specified as the lon0 argument of the TransverseMercator::Forward and TransverseMercator::Reverse functions. The latitude of origin is taken to be the equator. There is no provision in this class for specifying a false easting or false northing or a different latitude of origin. However these are can be simply included by the calling function. For example, the UTMUPS class applies the false easting and false northing for the UTM projections. A more complicated example is the British National Grid (EPSG:7405) which requires the use of a latitude of origin. This is implemented by the GeographicLib::OSGB class.
See TransverseMercator.cpp for more information on the implementation.
See Transverse Mercator projection for a discussion of this projection.
Example of use:
// Example of using the GeographicLib::TransverseMercator class
#include <iostream>
#include <exception>
#include <string>
#include <iomanip>
#include <GeographicLib/TransverseMercator.hpp>
using namespace std;
using namespace GeographicLib;
int main() {
  try {
    TransverseMercator proj(Constants::WGS84_a(), Constants::WGS84_f(),
                            Constants::UTM_k0());
    // Alternatively:
    // const TransverseMercator& proj = TransverseMercator::UTM();
    double lon0 = -75;          // Central meridian for UTM zone 18
    {
      // Sample forward calculation
      double lat = 40.3, lon = -74.7; // Princeton, NJ
      double x, y;
      proj.Forward(lon0, lat, lon, x, y);
      cout << x << " " << y << "\n";
    }
    {
      // Sample reverse calculation
      double x = 25e3, y = 4461e3;
      double lat, lon;
      proj.Reverse(lon0, x, y, lat, lon);
      cout << lat << " " << lon << "\n";
    }
  }
  catch (const exception& e) {
    cerr << "Caught exception: " << e.what() << "\n";
    return 1;
  }
  return 0;
}
TransverseMercatorProj is a command-line utility providing access to the functionality of TransverseMercator and TransverseMercatorExact.
Definition at line 89 of file TransverseMercator.hpp.
Constructor & Destructor Documentation
TransverseMercator()
GeographicLib::TransverseMercator::TransverseMercator (real a, real f, real k0)
Constructor for a ellipsoid with
Parameters
[in] a equatorial radius (meters).
[in] f flattening of ellipsoid. Setting f = 0 gives a sphere. Negative f gives a prolate ellipsoid. If f > 1, set flattening to 1/f.
[in] k0 central scale factor.
Exceptions
GeographicErr if a, (1 − f) a, or k0 is not positive.
Definition at line 48 of file TransverseMercator.cpp.
References GeographicLib::Math::isfinite().
Member Function Documentation
Forward() [1/2]
void GeographicLib::TransverseMercator::Forward (real lon0, real lat, real lon, real & x, real & y, real & gamma, real & k) const
Forward projection, from geographic to transverse Mercator.
Parameters
[in] lon0 central meridian of the projection (degrees).
[in] lat latitude of point (degrees).
[in] lon longitude of point (degrees).
[out] x easting of point (meters).
[out] y northing of point (meters).
[out] gamma meridian convergence at point (degrees).
[out] k scale of projection at point.
No false easting or northing is added. lat should be in the range [−90°, 90°].
Definition at line 353 of file TransverseMercator.cpp.
References GeographicLib::Math::AngDiff(), GeographicLib::Math::AngNormalize(), GeographicLib::Math::asinh(), GeographicLib::Math::atan2d(), GeographicLib::Math::hypot(), GeographicLib::Math::LatFix(), GeographicLib::Math::pi(), GeographicLib::Math::sincosd(), GeographicLib::Math::sq(), and GeographicLib::Math::taupf().
Referenced by GeographicLib::UTMUPS::Forward(), GeographicLib::OSGB::Forward(), and main().
Reverse() [1/2]
void GeographicLib::TransverseMercator::Reverse (real lon0, real x, real y, real & lat, real & lon, real & gamma, real & k) const
Reverse projection, from transverse Mercator to geographic.
Parameters
[in] lon0 central meridian of the projection (degrees).
[in] x easting of point (meters).
[in] y northing of point (meters).
[out] lat latitude of point (degrees).
[out] lon longitude of point (degrees).
[out] gamma meridian convergence at point (degrees).
[out] k scale of projection at point.
No false easting or northing is added. The value of lon returned is in the range [−180°, 180°).
Definition at line 515 of file TransverseMercator.cpp.
References GeographicLib::Math::AngNormalize(), GeographicLib::Math::atan2d(), GeographicLib::Math::atand(), GeographicLib::Math::hypot(), GeographicLib::Math::pi(), GeographicLib::Math::sq(), and GeographicLib::Math::tauf().
Referenced by main(), GeographicLib::UTMUPS::Reverse(), and GeographicLib::OSGB::Reverse().
Forward() [2/2]
void GeographicLib::TransverseMercator::Forward (real lon0, real lat, real lon, real & x, real & y) const inline
TransverseMercator::Forward without returning the convergence and scale.
Definition at line 150 of file TransverseMercator.hpp.
Reverse() [2/2]
void GeographicLib::TransverseMercator::Reverse (real lon0, real x, real y, real & lat, real & lon) const inline
TransverseMercator::Reverse without returning the convergence and scale.
Definition at line 159 of file TransverseMercator.hpp.
MajorRadius()
Math::real GeographicLib::TransverseMercator::MajorRadius () const inline
Returns
a the equatorial radius of the ellipsoid (meters). This is the value used in the constructor.
Definition at line 172 of file TransverseMercator.hpp.
Flattening()
Math::real GeographicLib::TransverseMercator::Flattening () const inline
Returns
f the flattening of the ellipsoid. This is the value used in the constructor.
Definition at line 178 of file TransverseMercator.hpp.
CentralScale()
Math::real GeographicLib::TransverseMercator::CentralScale () const inline
Returns
k0 central scale for the projection. This is the value of k0 used in the constructor and is the scale on the central meridian.
Definition at line 192 of file TransverseMercator.hpp.
UTM()
const TransverseMercator & GeographicLib::TransverseMercator::UTM () static
A global instantiation of TransverseMercator with the WGS84 ellipsoid and the UTM scale factor. However, unlike UTM, no false easting or northing is added.
Definition at line 280 of file TransverseMercator.cpp.
References GeographicLib::Constants::UTM_k0(), GeographicLib::Constants::WGS84_a(), and GeographicLib::Constants::WGS84_f().
Referenced by GeographicLib::UTMUPS::Forward(), and GeographicLib::UTMUPS::Reverse().
Friends And Related Function Documentation
Ellipsoid
friend class Ellipsoid friend
Definition at line 97 of file TransverseMercator.hpp.
The documentation for this class was generated from the following files:
TransverseMercator.hpp
TransverseMercator.cpp