GeographicLib: GeographicLib::Math Class Reference
GeographicLib::Math Class Reference
Mathematical functions needed by GeographicLib.
#include <GeographicLib/Math.hpp>
Public Types
typedef double extended
typedef double real
Static Public Member Functions
static int digits ()
static int set_digits (int ndigits)
static int digits10 ()
static int extra_digits ()
template<typename T >
static T pi ()
static real pi ()
template<typename T >
static T degree ()
static real degree ()
template<typename T >
static T sq (T x)
template<typename T >
static T hypot (T x, T y)
template<typename T >
static T expm1 (T x)
template<typename T >
static T log1p (T x)
template<typename T >
static T asinh (T x)
template<typename T >
static T atanh (T x)
template<typename T >
static T cbrt (T x)
template<typename T >
static T fma (T x, T y, T z)
template<typename T >
static void norm (T &x, T &y)
template<typename T >
static T sum (T u, T v, T &t)
template<typename T >
static T polyval (int N, const T p[], T x)
template<typename T >
static T AngNormalize (T x)
template<typename T >
static T AngNormalize2 (T x)
template<typename T >
static T LatFix (T x)
template<typename T >
static T AngDiff (T x, T y)
template<typename T >
static T AngRound (T x)
template<typename T >
static void sincosd (T x, T &sinx, T &cosx)
template<typename T >
static T sind (T x)
template<typename T >
static T cosd (T x)
template<typename T >
static T tand (T x)
template<typename T >
static T atan2d (T y, T x)
template<typename T >
static T atand (T x)
template<typename T >
static T eatanhe (T x, T es)
template<typename T >
static T taupf (T tau, T es)
template<typename T >
static T tauf (T taup, T es)
template<typename T >
static bool isfinite (T x)
template<typename T >
static T NaN ()
static real NaN ()
template<typename T >
static bool isnan (T x)
template<typename T >
static T infinity ()
static real infinity ()
template<typename T >
static T swab (T x)
Static Public Attributes
static const int extradigits
static const bool bigendian = GEOGRAPHICLIB_WORDS_BIGENDIAN
Detailed Description
Mathematical functions needed by GeographicLib.
Define mathematical functions in order to localize system dependencies and to provide generic versions of the functions. In addition define a real type to be used by GeographicLib.
Example of use:
// Example of using the GeographicLib::Math class
#include <iostream>
#include <exception>
#include <GeographicLib/Math.hpp>
using namespace std;
using namespace GeographicLib;
int main() {
  try {
    cout << Math::pi() << " " << Math::sq(Math::pi()) << "\n";
  }
  catch (const exception& e) {
    cerr << "Caught exception: " << e.what() << "\n";
    return 1;
  }
  return 0;
}
Definition at line 102 of file Math.hpp.
Member Typedef Documentation
extended
typedef double GeographicLib::Math::extended
Definition at line 119 of file Math.hpp.
real
typedef double GeographicLib::Math::real
The real type for GeographicLib. Nearly all the testing has been done with real = double. However, the algorithms should also work with float and long double (where available). (CAUTION: reasonable accuracy typically cannot be obtained using floats.)
Definition at line 129 of file Math.hpp.
Member Function Documentation
digits()
static int GeographicLib::Math::digits () inline static
Returns
the number of bits of precision in a real number.
Definition at line 145 of file Math.hpp.
Referenced by GeographicLib::MGRS::Forward().
set_digits()
static int GeographicLib::Math::set_digits (int ndigits) inline static
Set the binary precision of a real number.
Parameters
[in] ndigits the number of bits of precision.
Returns
the resulting number of bits of precision.
This only has an effect when GEOGRAPHICLIB_PRECISION == 5. See also Utility::set_digits for caveats about when this routine should be called.
Definition at line 163 of file Math.hpp.
Referenced by GeographicLib::Utility::set_digits().
digits10()
static int GeographicLib::Math::digits10 () inline static
Returns
the number of decimal digits of precision in a real number.
Definition at line 175 of file Math.hpp.
extra_digits()
static int GeographicLib::Math::extra_digits () inline static
Number of additional decimal digits of precision for real relative to double (0 for float).
Definition at line 187 of file Math.hpp.
Referenced by GeographicLib::GeoCoords::DMSRepresentation(), GeographicLib::DMS::Encode(), and GeographicLib::GeoCoords::GeoRepresentation().
pi() [1/2]
template<typename T > static T GeographicLib::Math::pi () inline static
Template Parameters
T the type of the returned value.
Returns
π.
Definition at line 216 of file Math.hpp.
Referenced by GeographicLib::Ellipsoid::Area(), GeographicLib::EllipticFunction::D(), GeographicLib::EllipticFunction::deltaD(), GeographicLib::EllipticFunction::deltaE(), GeographicLib::EllipticFunction::deltaEinv(), GeographicLib::EllipticFunction::deltaF(), GeographicLib::EllipticFunction::deltaG(), GeographicLib::EllipticFunction::deltaH(), GeographicLib::EllipticFunction::deltaPi(), GeographicLib::EllipticFunction::E(), GeographicLib::EllipticFunction::Einv(), GeographicLib::Geodesic::EllipsoidArea(), GeographicLib::GeodesicExact::EllipsoidArea(), GeographicLib::EllipticFunction::F(), GeographicLib::TransverseMercator::Forward(), GeographicLib::EllipticFunction::G(), GeographicLib::Geodesic::GenInverse(), GeographicLib::GeodesicExact::GenInverse(), GeographicLib::GeodesicLineExact::GeodesicLineExact(), GeographicLib::EllipticFunction::H(), GeographicLib::EllipticFunction::Pi(), GeographicLib::EllipticFunction::Reset(), GeographicLib::TransverseMercator::Reverse(), GeographicLib::EllipticFunction::RF(), GeographicLib::EllipticFunction::RG(), and GeographicLib::Ellipsoid::Volume().
pi() [2/2]
static real GeographicLib::Math::pi () inline static
A synonym for pi<real>().
Definition at line 224 of file Math.hpp.
degree() [1/2]
template<typename T > static T GeographicLib::Math::degree () inline static
Template Parameters
T the type of the returned value.
Returns
the number of radians in a degree.
Definition at line 230 of file Math.hpp.
Referenced by GeographicLib::Constants::arcminute(), GeographicLib::Constants::arcsecond(), GeographicLib::Constants::degree(), GeographicLib::GeodesicLineExact::EquatorialArc(), GeographicLib::MagneticModel::FieldComponents(), GeographicLib::CassiniSoldner::Forward(), GeographicLib::AlbersEqualArea::Forward(), GeographicLib::LambertConformalConic::Forward(), GeographicLib::TransverseMercatorExact::Forward(), GeographicLib::Geodesic::GenInverse(), GeographicLib::GeodesicExact::GenInverse(), GeographicLib::Rhumb::GenInverse(), GeographicLib::GeodesicLine::GenPosition(), GeographicLib::GeodesicLineExact::GenPosition(), GeographicLib::RhumbLine::GenPosition(), GeographicLib::Ellipsoid::InverseIsometricLatitude(), GeographicLib::Ellipsoid::InverseRectifyingLatitude(), GeographicLib::Ellipsoid::IsometricLatitude(), GeographicLib::AlbersEqualArea::Reverse(), GeographicLib::LambertConformalConic::Reverse(), GeographicLib::TransverseMercatorExact::Reverse(), GeographicLib::GravityModel::SphericalAnomaly(), GeographicLib::GravityCircle::SphericalAnomaly(), GeographicLib::JacobiConformal::x(), and GeographicLib::JacobiConformal::y().
degree() [2/2]
static real GeographicLib::Math::degree () inline static
A synonym for degree<real>().
Definition at line 237 of file Math.hpp.
sq()
template<typename T > static T GeographicLib::Math::sq (T x) inline static
Square a number.
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x
Returns
x2.
Definition at line 246 of file Math.hpp.
Referenced by GeographicLib::Ellipsoid::Area(), GeographicLib::MagneticModel::FieldComponents(), GeographicLib::NormalGravity::FlatteningToJ2(), GeographicLib::Ellipsoid::FlatteningToSecondEccentricitySq(), GeographicLib::Ellipsoid::FlatteningToThirdEccentricitySq(), GeographicLib::PolarStereographic::Forward(), GeographicLib::AlbersEqualArea::Forward(), GeographicLib::LambertConformalConic::Forward(), GeographicLib::TransverseMercator::Forward(), GeographicLib::Geodesic::GenInverse(), GeographicLib::GeodesicExact::GenInverse(), GeographicLib::GeodesicLine::GenPosition(), GeographicLib::GeodesicLineExact::GenPosition(), GeographicLib::GeodesicLine::GeodesicLine(), GeographicLib::GeodesicLineExact::GeodesicLineExact(), GeographicLib::GravityModel::GravityModel(), GeographicLib::NormalGravity::J2ToFlattening(), GeographicLib::Ellipsoid::MeridionalCurvatureRadius(), GeographicLib::Ellipsoid::NormalCurvatureRadius(), GeographicLib::NormalGravity::Phi(), GeographicLib::EllipticFunction::Reset(), GeographicLib::PolarStereographic::Reverse(), GeographicLib::AlbersEqualArea::Reverse(), GeographicLib::LambertConformalConic::Reverse(), GeographicLib::TransverseMercator::Reverse(), GeographicLib::EllipticFunction::RG(), GeographicLib::EllipticFunction::RJ(), GeographicLib::AlbersEqualArea::SetScale(), GeographicLib::NormalGravity::SurfaceGravity(), GeographicLib::Ellipsoid::TransverseCurvatureRadius(), GeographicLib::NormalGravity::V0(), GeographicLib::Ellipsoid::Volume(), GeographicLib::JacobiConformal::x(), and GeographicLib::JacobiConformal::y().
hypot()
template<typename T > static T GeographicLib::Math::hypot (T x, T y) inline static
The hypotenuse function avoiding underflow and overflow.
Template Parameters
T the type of the arguments and the returned value.
Parameters
[in] x
[in] y
Returns
sqrt(x2 + y2).
Definition at line 257 of file Math.hpp.
Referenced by GeographicLib::GravityModel::Circle(), GeographicLib::Ellipsoid::CircleHeight(), GeographicLib::Ellipsoid::CircleRadius(), GeographicLib::MagneticModel::FieldComponents(), GeographicLib::PolarStereographic::Forward(), GeographicLib::TransverseMercator::Forward(), GeographicLib::Geodesic::GenInverse(), GeographicLib::GeodesicExact::GenInverse(), GeographicLib::Rhumb::GenInverse(), GeographicLib::GeodesicLine::GenPosition(), GeographicLib::GeodesicLineExact::GenPosition(), GeographicLib::GeodesicLine::GeodesicLine(), GeographicLib::GeodesicLineExact::GeodesicLineExact(), GeographicLib::GravityModel::GeoidHeight(), GeographicLib::PolarStereographic::Reverse(), GeographicLib::AzimuthalEquidistant::Reverse(), GeographicLib::Gnomonic::Reverse(), GeographicLib::AlbersEqualArea::Reverse(), GeographicLib::LambertConformalConic::Reverse(), GeographicLib::TransverseMercator::Reverse(), GeographicLib::GravityModel::SphericalAnomaly(), and GeographicLib::NormalGravity::V0().
expm1()
template<typename T > static T GeographicLib::Math::expm1 (T x) inline static
exp(x) − 1 accurate near x = 0.
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x
Returns
exp(x) − 1.
Definition at line 279 of file Math.hpp.
References GEOGRAPHICLIB_VOLATILE.
log1p()
template<typename T > static T GeographicLib::Math::log1p (T x) inline static
log(1 + x) accurate near x = 0.
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x
Returns
log(1 + x).
Definition at line 302 of file Math.hpp.
References GEOGRAPHICLIB_VOLATILE.
Referenced by GeographicLib::LambertConformalConic::Reverse().
asinh()
template<typename T > static T GeographicLib::Math::asinh (T x) inline static
The inverse hyperbolic sine function.
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x
Returns
asinh(x).
Definition at line 325 of file Math.hpp.
Referenced by GeographicLib::LambertConformalConic::Forward(), GeographicLib::TransverseMercator::Forward(), GeographicLib::Ellipsoid::IsometricLatitude(), and GeographicLib::EllipticFunction::RC().
atanh()
template<typename T > static T GeographicLib::Math::atanh (T x) inline static
The inverse hyperbolic tangent function.
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x
Returns
atanh(x).
Definition at line 342 of file Math.hpp.
Referenced by GeographicLib::Ellipsoid::Area().
cbrt()
template<typename T > static T GeographicLib::Math::cbrt (T x) inline static
The cube root function.
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x
Returns
the real cube root of x.
Definition at line 359 of file Math.hpp.
fma()
template<typename T > static T GeographicLib::Math::fma (T x, T y, T z) inline static
Fused multiply and add.
Template Parameters
T the type of the arguments and the returned value.
Parameters
[in] x
[in] y
[in] z
Returns
xy + z, correctly rounded (on those platforms with support for the fma instruction).
On platforms without the fma instruction, no attempt is made to improve on the result of a rounded multiplication followed by a rounded addition.
Definition at line 383 of file Math.hpp.
Referenced by GeographicLib::Accumulator< T >::operator*=().
norm()
template<typename T > static void GeographicLib::Math::norm (T & x, T & y) inline static
Normalize a two-vector.
Template Parameters
T the type of the argument and the returned value.
Parameters
[in,out] x on output set to x/hypot(x, y).
[in,out] y on output set to y/hypot(x, y).
Definition at line 398 of file Math.hpp.
Referenced by GeographicLib::Geodesic::GenInverse(), GeographicLib::GeodesicExact::GenInverse(), GeographicLib::GeodesicLine::GeodesicLine(), GeographicLib::GeodesicLineExact::GeodesicLineExact(), and GeographicLib::CassiniSoldner::Reset().
sum()
template<typename T > static T GeographicLib::Math::sum (T u, T v, T & t) inline static
The error-free sum of two numbers.
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] u
[in] v
[out] t the exact error given by (u + v) - s.
Returns
s = round(u + v).
See D. E. Knuth, TAOCP, Vol 2, 4.2.2, Theorem B. (Note that t can be the same as one of the first two arguments.)
Definition at line 413 of file Math.hpp.
References GEOGRAPHICLIB_VOLATILE.
polyval()
template<typename T > static T GeographicLib::Math::polyval (int N, const T p[], T x) inline static
Evaluate a polynomial.
Template Parameters
T the type of the arguments and returned value.
Parameters
[in] N the order of the polynomial.
[in] p the coefficient array (of size N + 1).
[in] x the variable.
Returns
the value of the polynomial.
Evaluate y = ∑n=0..N pn xN−n. Return 0 if N < 0. Return p0, if N = 0 (even if x is infinite or a nan). The evaluation uses Horner's method.
Definition at line 439 of file Math.hpp.
AngNormalize()
template<typename T > static T GeographicLib::Math::AngNormalize (T x) inline static
Normalize an angle.
Template Parameters
T the type of the argument and returned value.
Parameters
[in] x the angle in degrees.
Returns
the angle reduced to the range [−180°, 180°).
The range of x is unrestricted.
Definition at line 451 of file Math.hpp.
Referenced by GeographicLib::PolygonAreaT< GeodType >::AddEdge(), GeographicLib::PolygonAreaT< GeodType >::AddPoint(), GeographicLib::Geoid::CacheArea(), GeographicLib::DMS::DecodeAzimuth(), GeographicLib::PolarStereographic::Forward(), GeographicLib::Geohash::Forward(), GeographicLib::GARS::Forward(), GeographicLib::Georef::Forward(), GeographicLib::CassiniSoldner::Forward(), GeographicLib::TransverseMercator::Forward(), GeographicLib::GeodesicLine::GenPosition(), GeographicLib::GeodesicLineExact::GenPosition(), GeographicLib::RhumbLine::GenPosition(), GeographicLib::GeoCoords::Reset(), GeographicLib::LocalCartesian::Reset(), GeographicLib::PolarStereographic::Reverse(), GeographicLib::AlbersEqualArea::Reverse(), GeographicLib::LambertConformalConic::Reverse(), GeographicLib::TransverseMercator::Reverse(), GeographicLib::TransverseMercatorExact::Reverse(), and GeographicLib::PolygonAreaT< GeodType >::TestEdge().
AngNormalize2()
template<typename T > static T GeographicLib::Math::AngNormalize2 (T x) inline static
Normalize an arbitrary angle.
Template Parameters
T the type of the argument and returned value.
Parameters
[in] x the angle in degrees.
Returns
the angle reduced to the range [−180°, 180°).
DEPRECATED: use AngNormalize instead.
Definition at line 471 of file Math.hpp.
LatFix()
template<typename T > static T GeographicLib::Math::LatFix (T x) inline static
Normalize a latitude.
Template Parameters
T the type of the argument and returned value.
Parameters
[in] x the angle in degrees.
Returns
x if it is in the range [−90°, 90°], otherwise return NaN.
Definition at line 482 of file Math.hpp.
Referenced by GeographicLib::PolygonAreaT< GeodType >::AddPoint(), GeographicLib::Ellipsoid::AuthalicLatitude(), GeographicLib::Geoid::CacheArea(), GeographicLib::Ellipsoid::CircleHeight(), GeographicLib::Ellipsoid::CircleRadius(), GeographicLib::Ellipsoid::ConformalLatitude(), GeographicLib::PolarStereographic::Forward(), GeographicLib::AlbersEqualArea::Forward(), GeographicLib::LambertConformalConic::Forward(), GeographicLib::TransverseMercator::Forward(), GeographicLib::TransverseMercatorExact::Forward(), GeographicLib::Geodesic::GenInverse(), GeographicLib::GeodesicExact::GenInverse(), GeographicLib::Ellipsoid::GeocentricLatitude(), GeographicLib::Ellipsoid::InverseAuthalicLatitude(), GeographicLib::Ellipsoid::InverseConformalLatitude(), GeographicLib::Ellipsoid::InverseGeocentricLatitude(), GeographicLib::Ellipsoid::InverseParametricLatitude(), GeographicLib::Ellipsoid::IsometricLatitude(), GeographicLib::Ellipsoid::MeridionalCurvatureRadius(), GeographicLib::Ellipsoid::NormalCurvatureRadius(), GeographicLib::Ellipsoid::ParametricLatitude(), GeographicLib::LocalCartesian::Reset(), GeographicLib::NormalGravity::SurfaceGravity(), and GeographicLib::Ellipsoid::TransverseCurvatureRadius().
AngDiff()
template<typename T > static T GeographicLib::Math::AngDiff (T x, T y) inline static
Difference of two angles reduced to [−180°, 180°]
Template Parameters
T the type of the arguments and returned value.
Parameters
[in] x the first angle in degrees.
[in] y the second angle in degrees.
Returns
y − x, reduced to the range [−180°, 180°].
The result is equivalent to computing the difference exactly, reducing it to (−180°, 180°] and rounding the result. Note that this prescription allows −180° to be returned (e.g., if x is tiny and negative and y = 180°).
Definition at line 499 of file Math.hpp.
Referenced by GeographicLib::CassiniSoldner::Forward(), GeographicLib::AlbersEqualArea::Forward(), GeographicLib::LambertConformalConic::Forward(), GeographicLib::TransverseMercator::Forward(), GeographicLib::TransverseMercatorExact::Forward(), GeographicLib::Geodesic::GenInverse(), GeographicLib::GeodesicExact::GenInverse(), and GeographicLib::Rhumb::GenInverse().
AngRound()
template<typename T > static T GeographicLib::Math::AngRound (T x) inline static
Coarsen a value close to zero.
Template Parameters
T the type of the argument and returned value.
Parameters
[in] x
Returns
the coarsened value.
The makes the smallest gap in x = 1/16 - nextafter(1/16, 0) = 1/257 for reals = 0.7 pm on the earth if x is an angle in degrees. (This is about 1000 times more resolution than we get with angles around 90°.) We use this to avoid having to deal with near singular cases when x is non-zero but tiny (e.g., 10−200). This also converts -0 to +0.
Definition at line 530 of file Math.hpp.
References GEOGRAPHICLIB_VOLATILE.
Referenced by GeographicLib::Geodesic::GenInverse(), GeographicLib::GeodesicExact::GenInverse(), GeographicLib::GeodesicLine::GeodesicLine(), and GeographicLib::GeodesicLineExact::GeodesicLineExact().
sincosd()
template<typename T > static void GeographicLib::Math::sincosd (T x, T & sinx, T & cosx) inline static
Evaluate the sine and cosine function with the argument in degrees
Template Parameters
T the type of the arguments.
Parameters
[in] x in degrees.
[out] sinx sin(x).
[out] cosx cos(x).
The results obey exactly the elementary properties of the trigonometric functions, e.g., sin 9° = cos 81° = − sin 123456789°.
Definition at line 559 of file Math.hpp.
Referenced by GeographicLib::AlbersEqualArea::AlbersEqualArea(), GeographicLib::GravityCircle::Disturbance(), GeographicLib::EllipticFunction::Ed(), GeographicLib::PolarStereographic::Forward(), GeographicLib::CassiniSoldner::Forward(), GeographicLib::AzimuthalEquidistant::Forward(), GeographicLib::Gnomonic::Forward(), GeographicLib::AlbersEqualArea::Forward(), GeographicLib::LambertConformalConic::Forward(), GeographicLib::TransverseMercator::Forward(), GeographicLib::Geodesic::GenInverse(), GeographicLib::GeodesicExact::GenInverse(), GeographicLib::GeodesicLine::GenPosition(), GeographicLib::GeodesicLine::GeodesicLine(), GeographicLib::GeodesicLineExact::GeodesicLineExact(), GeographicLib::GravityCircle::GeoidHeight(), GeographicLib::GravityCircle::Gravity(), GeographicLib::LambertConformalConic::LambertConformalConic(), GeographicLib::Ellipsoid::NormalCurvatureRadius(), GeographicLib::CircularEngine::operator()(), GeographicLib::CassiniSoldner::Reset(), GeographicLib::LocalCartesian::Reset(), GeographicLib::GravityCircle::SphericalAnomaly(), GeographicLib::GravityCircle::T(), GeographicLib::GravityCircle::V(), GeographicLib::GravityCircle::W(), GeographicLib::JacobiConformal::x(), and GeographicLib::JacobiConformal::y().
sind()
template<typename T > static T GeographicLib::Math::sind (T x) inline static
Evaluate the sine function with the argument in degrees
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x in degrees.
Returns
sin(x).
Definition at line 597 of file Math.hpp.
Referenced by GeographicLib::Ellipsoid::MeridionalCurvatureRadius(), GeographicLib::Ellipsoid::NormalCurvatureRadius(), GeographicLib::NormalGravity::SurfaceGravity(), and GeographicLib::Ellipsoid::TransverseCurvatureRadius().
cosd()
template<typename T > static T GeographicLib::Math::cosd (T x) inline static
Evaluate the cosine function with the argument in degrees
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x in degrees.
Returns
cos(x).
Definition at line 625 of file Math.hpp.
tand()
template<typename T > static T GeographicLib::Math::tand (T x) inline static
Evaluate the tangent function with the argument in degrees
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x in degrees.
Returns
tan(x).
If x = ±90°, then a suitably large (but finite) value is returned.
Definition at line 656 of file Math.hpp.
Referenced by GeographicLib::Ellipsoid::AuthalicLatitude(), GeographicLib::Ellipsoid::CircleHeight(), GeographicLib::Ellipsoid::CircleRadius(), GeographicLib::Ellipsoid::ConformalLatitude(), GeographicLib::PolarStereographic::Forward(), GeographicLib::TransverseMercatorExact::Forward(), GeographicLib::Ellipsoid::GeocentricLatitude(), GeographicLib::Ellipsoid::InverseAuthalicLatitude(), GeographicLib::Ellipsoid::InverseConformalLatitude(), GeographicLib::Ellipsoid::InverseGeocentricLatitude(), GeographicLib::Ellipsoid::InverseParametricLatitude(), GeographicLib::Ellipsoid::IsometricLatitude(), and GeographicLib::Ellipsoid::ParametricLatitude().
atan2d()
template<typename T > static T GeographicLib::Math::atan2d (T y, T x) inline static
Evaluate the atan2 function with the result in degrees
Template Parameters
T the type of the arguments and the returned value.
Parameters
[in] y
[in] x
Returns
atan2(y, x) in degrees.
The result is in the range [−180° 180°). N.B., atan2d(±0, −1) = −180°; atan2d(+ε, −1) = +180°, for ε positive and tiny; atan2d(±0, 1) = ±0°.
Definition at line 676 of file Math.hpp.
Referenced by GeographicLib::GeodesicLine::EquatorialArc(), GeographicLib::GeodesicLine::EquatorialAzimuth(), GeographicLib::GeodesicLineExact::EquatorialAzimuth(), GeographicLib::MagneticModel::FieldComponents(), GeographicLib::TransverseMercator::Forward(), GeographicLib::Geodesic::GenInverse(), GeographicLib::GeodesicExact::GenInverse(), GeographicLib::Rhumb::GenInverse(), GeographicLib::GeodesicLine::GenPosition(), GeographicLib::GeodesicLineExact::GenPosition(), GeographicLib::PolarStereographic::Reverse(), GeographicLib::AzimuthalEquidistant::Reverse(), GeographicLib::Gnomonic::Reverse(), and GeographicLib::TransverseMercator::Reverse().
atand()
template<typename T > static T GeographicLib::Math::atand (T x) inline static
Evaluate the atan function with the result in degrees
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x
Returns
atan(x) in degrees.
Definition at line 708 of file Math.hpp.
Referenced by GeographicLib::Ellipsoid::AuthalicLatitude(), GeographicLib::Ellipsoid::ConformalLatitude(), GeographicLib::Ellipsoid::GeocentricLatitude(), GeographicLib::Ellipsoid::InverseAuthalicLatitude(), GeographicLib::Ellipsoid::InverseConformalLatitude(), GeographicLib::Ellipsoid::InverseGeocentricLatitude(), GeographicLib::Ellipsoid::InverseIsometricLatitude(), GeographicLib::Ellipsoid::InverseParametricLatitude(), GeographicLib::Ellipsoid::ParametricLatitude(), GeographicLib::PolarStereographic::Reverse(), GeographicLib::AlbersEqualArea::Reverse(), GeographicLib::LambertConformalConic::Reverse(), and GeographicLib::TransverseMercator::Reverse().
eatanhe()
template<typename T > static T GeographicLib::Math::eatanhe (T x, T es) static
Evaluate e atanh(e x)
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x
[in] es the signed eccentricity = sign(e2) sqrt(|e2|)
Returns
e atanh(e x)
If e2 is negative (e is imaginary), the expression is evaluated in terms of atan.
Referenced by GeographicLib::LambertConformalConic::Forward().
taupf()
template<typename T > static T GeographicLib::Math::taupf (T tau, T es) static
tanχ in terms of tanφ
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] tau τ = tanφ
[in] es the signed eccentricity = sign(e2) sqrt(|e2|)
Returns
τ′ = tanχ
See Eqs. (7–9) of C. F. F. Karney, Transverse Mercator with an accuracy of a few nanometers, J. Geodesy 85(8), 475–485 (Aug. 2011) (preprint arXiv:1002.1417).
Referenced by GeographicLib::Ellipsoid::ConformalLatitude(), GeographicLib::PolarStereographic::Forward(), GeographicLib::TransverseMercator::Forward(), GeographicLib::TransverseMercatorExact::Forward(), and GeographicLib::Ellipsoid::IsometricLatitude().
tauf()
template<typename T > static T GeographicLib::Math::tauf (T taup, T es) static
tanφ in terms of tanχ
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] taup τ′ = tanχ
[in] es the signed eccentricity = sign(e2) sqrt(|e2|)
Returns
τ = tanφ
See Eqs. (19–21) of C. F. F. Karney, Transverse Mercator with an accuracy of a few nanometers, J. Geodesy 85(8), 475–485 (Aug. 2011) (preprint arXiv:1002.1417).
Referenced by GeographicLib::TransverseMercatorExact::Forward(), GeographicLib::Ellipsoid::InverseConformalLatitude(), GeographicLib::Ellipsoid::InverseIsometricLatitude(), GeographicLib::PolarStereographic::Reverse(), GeographicLib::LambertConformalConic::Reverse(), GeographicLib::TransverseMercator::Reverse(), and GeographicLib::TransverseMercatorExact::Reverse().
isfinite()
template<typename T > static bool GeographicLib::Math::isfinite (T x) inline static
Test for finiteness.
Template Parameters
T the type of the argument.
Parameters
[in] x
Returns
true if number is finite, false if NaN or infinite.
Definition at line 768 of file Math.hpp.
Referenced by GeographicLib::AlbersEqualArea::AlbersEqualArea(), GeographicLib::DMS::Encode(), GeographicLib::Geocentric::Geocentric(), GeographicLib::Geodesic::Geodesic(), GeographicLib::GeodesicExact::GeodesicExact(), GeographicLib::LambertConformalConic::LambertConformalConic(), GeographicLib::NormalGravity::NormalGravity(), GeographicLib::PolarStereographic::PolarStereographic(), GeographicLib::LambertConformalConic::Reverse(), GeographicLib::AlbersEqualArea::SetScale(), GeographicLib::LambertConformalConic::SetScale(), GeographicLib::PolarStereographic::SetScale(), GeographicLib::Utility::str(), GeographicLib::TransverseMercator::TransverseMercator(), and GeographicLib::TransverseMercatorExact::TransverseMercatorExact().
NaN() [1/2]
template<typename T > static T GeographicLib::Math::NaN () inline static
The NaN (not a number)
Template Parameters
T the type of the returned value.
Returns
NaN if available, otherwise return the max real of type T.
Definition at line 783 of file Math.hpp.
Referenced by GeographicLib::NormalGravity::AngularVelocity(), GeographicLib::GeodesicLine::Azimuth(), GeographicLib::GeodesicLineExact::Azimuth(), GeographicLib::GravityModel::Circle(), GeographicLib::PolygonAreaT< GeodType >::Clear(), GeographicLib::NormalGravity::DynamicalFormFactor(), GeographicLib::GeodesicLine::EquatorialArc(), GeographicLib::GeodesicLineExact::EquatorialArc(), GeographicLib::GeodesicLine::EquatorialAzimuth(), GeographicLib::GeodesicLineExact::EquatorialAzimuth(), GeographicLib::NormalGravity::EquatorialGravity(), GeographicLib::Geocentric::Flattening(), GeographicLib::GeodesicLine::Flattening(), GeographicLib::GeodesicLineExact::Flattening(), GeographicLib::GravityCircle::Flattening(), GeographicLib::MagneticCircle::Flattening(), GeographicLib::NormalGravity::Flattening(), GeographicLib::UTMUPS::Forward(), GeographicLib::Gnomonic::Forward(), GeographicLib::GeodesicLine::GenPosition(), GeographicLib::GeodesicLineExact::GenPosition(), GeographicLib::RhumbLine::GenPosition(), GeographicLib::GravityCircle::GeoidHeight(), GeographicLib::NormalGravity::GravityFlattening(), GeographicLib::OSGB::GridReference(), GeographicLib::GravityCircle::Height(), GeographicLib::MagneticCircle::Height(), GeographicLib::GeodesicLine::Latitude(), GeographicLib::GeodesicLineExact::Latitude(), GeographicLib::GravityCircle::Latitude(), GeographicLib::MagneticCircle::Latitude(), GeographicLib::GeodesicLine::Longitude(), GeographicLib::GeodesicLineExact::Longitude(), GeographicLib::Geocentric::MajorRadius(), GeographicLib::GeodesicLine::MajorRadius(), GeographicLib::GeodesicLineExact::MajorRadius(), GeographicLib::GravityCircle::MajorRadius(), GeographicLib::MagneticCircle::MajorRadius(), GeographicLib::NormalGravity::MajorRadius(), GeographicLib::NormalGravity::MassConstant(), GeographicLib::NormalGravity::PolarGravity(), GeographicLib::GARS::Reverse(), GeographicLib::Geohash::Reverse(), GeographicLib::Georef::Reverse(), GeographicLib::MGRS::Reverse(), GeographicLib::UTMUPS::Reverse(), GeographicLib::Gnomonic::Reverse(), GeographicLib::GravityCircle::SphericalAnomaly(), GeographicLib::NormalGravity::SurfacePotential(), GeographicLib::PolygonAreaT< GeodType >::TestEdge(), and GeographicLib::MagneticCircle::Time().
NaN() [2/2]
static real GeographicLib::Math::NaN () inline static
A synonym for NaN<real>().
Definition at line 791 of file Math.hpp.
isnan()
template<typename T > static bool GeographicLib::Math::isnan (T x) inline static
Test for NaN.
Template Parameters
T the type of the argument.
Parameters
[in] x
Returns
true if argument is a NaN.
Definition at line 800 of file Math.hpp.
Referenced by GeographicLib::MGRS::Forward(), GeographicLib::Geohash::Forward(), GeographicLib::GARS::Forward(), GeographicLib::Georef::Forward(), GeographicLib::GeoCoords::GeoRepresentation(), GeographicLib::OSGB::GridReference(), GeographicLib::UTMUPS::Reverse(), and GeographicLib::UTMUPS::StandardZone().
infinity() [1/2]
template<typename T > static T GeographicLib::Math::infinity () inline static
Infinity
Template Parameters
T the type of the returned value.
Returns
infinity if available, otherwise return the max real.
Definition at line 814 of file Math.hpp.
Referenced by GeographicLib::EllipticFunction::Reset().
infinity() [2/2]
static real GeographicLib::Math::infinity () inline static
A synonym for infinity<real>().
Definition at line 822 of file Math.hpp.
swab()
template<typename T > static T GeographicLib::Math::swab (T x) inline static
Swap the bytes of a quantity
Template Parameters
T the type of the argument and the returned value.
Parameters
[in] x
Returns
x with its bytes swapped.
Definition at line 831 of file Math.hpp.
Member Data Documentation
extradigits
const int GeographicLib::Math::extradigits static
Initial value:
=
      std::numeric_limits<real>::digits10 >
      std::numeric_limits<double>::digits10 ?
      std::numeric_limits<real>::digits10 -
      std::numeric_limits<double>::digits10 : 0
Number of additional decimal digits of precision of real relative to double (0 for float).
DEPRECATED: use extra_digits() instead
Definition at line 200 of file Math.hpp.
bigendian
const bool GeographicLib::Math::bigendian = GEOGRAPHICLIB_WORDS_BIGENDIAN static
true if the machine is big-endian.
Definition at line 210 of file Math.hpp.
Referenced by GeographicLib::Utility::readarray(), and GeographicLib::Utility::writearray().
The documentation for this class was generated from the following file:
Math.hpp