GeographicLib: GeodSolve.cpp File Reference
GeodSolve.cpp File Reference
Command line utility for geodesic calculations.
#include <iostream>
#include <sstream>
#include <string>
#include <fstream>
#include <GeographicLib/Geodesic.hpp>
#include <GeographicLib/GeodesicLine.hpp>
#include <GeographicLib/GeodesicExact.hpp>
#include <GeographicLib/GeodesicLineExact.hpp>
#include <GeographicLib/DMS.hpp>
#include <GeographicLib/Utility.hpp>
#include "GeodSolve.usage"
Typedefs
typedef GeographicLib::Math::real real
Functions
std::string LatLonString (real lat, real lon, int prec, bool dms, char dmssep, bool longfirst)
std::string AzimuthString (real azi, int prec, bool dms, char dmssep)
std::string DistanceStrings (real s12, real a12, bool full, bool arcmode, int prec, bool dms)
real ReadDistance (const std::string &s, bool arcmode)
int main (int argc, char *argv[])
Detailed Description
Command line utility for geodesic calculations.
Copyright (c) Charles Karney (2009-2015) charl.nosp@m.es@k.nosp@m.arney.nosp@m..com and licensed under the MIT/X11 License. For more information, see http://geographiclib.sourceforge.net/
See the man page for usage information.
Definition in file GeodSolve.cpp.
Typedef Documentation
real
typedef GeographicLib::Math::real real
Definition at line 32 of file GeodSolve.cpp.
Function Documentation
LatLonString()
std::string LatLonString (real lat, real lon, int prec, bool dms, char dmssep, bool longfirst)
Definition at line 34 of file GeodSolve.cpp.
Referenced by main().
AzimuthString()
std::string AzimuthString (real azi, int prec, bool dms, char dmssep)
Definition at line 46 of file GeodSolve.cpp.
Referenced by main().
DistanceStrings()
std::string DistanceStrings (real s12, real a12, bool full, bool arcmode, int prec, bool dms)
Definition at line 52 of file GeodSolve.cpp.
Referenced by main().
ReadDistance()
real ReadDistance (const std::string & s, bool arcmode)
Definition at line 65 of file GeodSolve.cpp.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 70 of file GeodSolve.cpp.
References AzimuthString(), DistanceStrings(), GeographicLib::GeodesicExact::GenDirect(), GeographicLib::GeodesicExact::GenInverse(), GeographicLib::GeodesicLine::GenPosition(), GeographicLib::GeodesicLineExact::GenPosition(), LatLonString(), GeographicLib::GeodesicExact::Line(), and ReadDistance().