all: build

AR      = ar -r
CAT     = cat
CC      = gcc
CXX     = g++
DOC     = doxygen
ECHO    = $(SILENT) echo
LN      = ln -s
MKDIR   = mkdir -p
## MOC: see below.
RANLIB  = ranlib
RM      = rm -rf
SHELL   = bash
SILENT  = @
TAR	= tar
## UIC: see below.


## Generate version information about compiler
GCC_VERSION=$(shell LANG=C gcc -v 2>&1 | grep "gcc version" | awk '{ print $3 }')
GCC_VERSION_MAJOR=$(shell LANG=C gcc -v 2>&1 | grep "gcc version" | awk '{ print $$3 }' | awk -F. '{ print $$1 }')

#COMPILE_FLAGS=
## All Warnings & enable exception handling & enable pthreads
CFLAGS1   = -Wall -DLinux -DSHARED_MEMORY -fconserve-space
CFLAGS1  += -fexceptions -ftemplate-depth-25
CFLAGS1  += -Wno-deprecated

## debug
CFLAGS   = $(CFLAGS1)

## Package-wide basic log level
LOG_LEVEL = 10

CFLAGS += -g3


## Enable styled output?
CFLAGS += -DENABLE_OUTPUT_STYLING

## Enable introspection?
CFLAGS += -DENABLE_INTROSPECTION

## Optimization. "-O3" includes the option "-finline-functions"
CFLAGS += -O3


#LINK FLAGS=
# LINKFLAGS= $(shell if [ "`grep "Fedora Core release 4" /etc/redhat-release`"  != "" ]; then \
# 			if [ -d /lib/obsolete/linuxthreads ]; then \
# 				echo "-Wl,-rpath-link,/lib/obsolete/linuxthreads,-R/lib/obsolete/linuxthreads" ; \
# 			fi ; \
# 		fi)


## Libraries
QT_DIR	      = $(QTDIR)
BEESOFT_DIR   = $(BASEPREFIX)/src/extlib/beesoft-1.3.6-rh7.1

## QT special compilers
UIC	      = $(QT_DIR)/bin/uic
MOC	      = $(QT_DIR)/bin/moc


# SHARED = -static
# SHARED = -shared


# Lots of directories...
BIN_PATH     = $(BASEPREFIX)/bin
DOC_PATH     = $(BASEPREFIX)/doc
LIB_PATH     = $(BASEPREFIX)/lib
DEPLOY_PATH  = $(BASEPREFIX)/deploy
OBS_DIR      = .obj
DEPS_DIR     = .deps


# lib path for linking
LIB_DIR       = -L$(LIB_PATH)
LIB_DIR      += -L/usr/lib
LIB_DIR      += -L/usr/local/lib
LIB_DIR      += -L/usr/X11/lib
LIB_DIR      += -L/usr/X11R6/lib
LIB_DIR      += -L$(BEESOFT_DIR)/lib
LIB_DIR	     += -L$(QT_DIR)/lib
# LIB_DIR      += -L/usr/lib/linuxthreads


### INCLUDES ##############
INCLUDES     = -I$(BASEPREFIX)/src
# INCLUDES     += -I$(BASEPREFIX)/src/utils
INCLUDES    += -I.
# INC_IQUOTE   = $(shell if [ "$(GCC_VERSION_MAJOR)" = "4" ]; then echo "-iquote."; else echo "-I. -I-"; fi)
# INCLUDES    += $(INC_IQUOTE)
# INCLUDES    += -I/usr/include/linuxthreads
INCLUDES    += -I$(BEESOFT_DIR)/include/
INCLUDES    += -I$(QT_DIR)/include


#################################################################
##               S H A R E D   L I B R A R I E S               ##
#################################################################

CFLAGS_SHAREDLIBS = -Wl,-R.,-R/usr/local/lib,-R$(QT_DIR)/lib

# USE_SHARED_LIBS = yes
ifneq ($(USE_SHARED_LIBS),)
CFLAGS_SHAREDLIBS += -R../lib
#,-R$(A3D_PATH)/lib,
endif

LINKFLAGS += $(CFLAGS_SHAREDLIBS) -pthread


### Library names ###########
# LIBS_CGAL         = CGAL
# ifneq ($(MODE_USE_QT),)
# LIBS_CGAL_QT      = CGALQt
LIBS_QT           = qt-mt
# endif
LIBS_OPENGL       = GLU GL
LIBS_STDCPP       = stdc++
LIBS_XML          = xml2


### Silent colors ###########
#
BLACK           = $(SILENT) tput setaf 0
BG_BLACK        = $(SILENT) tput setab 0
DARKGREY        = $(SILENT) tput bold ; tput setaf 0
LIGHTGREY       = $(SILENT) tput setaf 7
BG_LIGHTGREY    = $(SILENT) tput setab 7
WHITE           = $(SILENT) tput bold ; tput setaf 7
#
RED             = $(SILENT) tput setaf 1
BG_RED          = $(SILENT) tput setab 1
BRIGHTRED       = $(SILENT) tput bold ; tput setaf 1
GREEN           = $(SILENT) tput setaf 2
BG_GREEN        = $(SILENT) tput setab 2
BRIGHTGREEN     = $(SILENT) tput bold ; tput setaf 2
BROWN           = $(SILENT) tput setaf 3
BG_BROWN        = $(SILENT) tput setab 3
YELLOW          = $(SILENT) tput bold ; tput setaf 3
BLUE            = $(SILENT) tput setaf 4
BG_BLUE         = $(SILENT) tput setab 4
BRIGHTBLUE      = $(SILENT) tput bold ; tput setaf 4
PURPLE          = $(SILENT) tput setaf 5
BG_PURPLE       = $(SILENT) tput setab 5
PINK            = $(SILENT) tput bold ; tput setaf 5
CYAN            = $(SILENT) tput setaf 6
BG_CYAN         = $(SILENT) tput setab 6
BRIGHTCYAN      = $(SILENT) tput bold ; tput setaf 6
#
NORMAL          = $(SILENT) tput sgr0
RESET           = $(SILENT) tput sgr0
#

### macro colors ##########

EECHO   = echo
RRED    = tput setaf 1 ; tput bold
GGREEN  = tput setaf 2 ; tput bold
YYELLOW = tput setaf 3 ; tput bold
BLINK   = tput blink
NNORMAL = tput sgr0
